# This is a basic workflow to help you get started with Actions

name: installer-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
    #branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer on mac
  call-macos-build:
    uses: ./.github/workflows/build-macos.yml
          
  call-linux-build:
    uses: ./.github/workflows/build-linux.yml
    
  call-windows-build:
    uses: ./.github/workflows/build-windows.yml
    
  # Using the outputs of the build
  deploy-builds: 
    runs-on: ubuntu-latest
    needs: [call-macos-build, call-linux-build, call-windows-build]
    steps:
      - run: echo ${{ needs.call-macos-build.outputs.build-file }}
      - run: echo ${{ needs.call-linux-build.outputs.build-file }}
      - run: echo ${{ needs.call-windows-build.outputs.build-file }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.call-macos-build.outputs.build-file }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.call-linux-build.outputs.build-file }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.call-windows-build.outputs.build-file }}
      - name: Output Listing
        run: ls -la

